
- name: Install required packages for Docker in RedHat systems
  dnf:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Install Docker packages in Amazon like systems
  dnf:
    name:
      - docker
      - containerd
    state: latest
