plugin: amazon.aws.ec2
regions:
  - "{{ lookup('env', 'AWS_REGION') }}"
filters:
  tag:Name: "{{ lookup('env', 'INSTANCE_NAME') }}"
  instance-state-name: running
hostnames:
  - instance_id
compose:
  ansible_connection: amazon.aws.aws_ssm
  ansible_aws_ssm_region: "{{ lookup('env', 'AWS_REGION') }}"
  ansible_aws_ssm_bucket_name: "{{ lookup('env', 'AWS_SSM_BUCKET') }}"
  env_type: "{{ lookup('env', 'ENV_TYPE') }}"
  region: "{{ lookup('env', 'AWS_REGION') }}"
  dump_type: "{{ lookup('env', 'DUMP_TYPE') }}"
  server_username: "{{ lookup('env', 'SERVER_USERNAME') }}"
  projet_client: "{{ lookup('env', 'PROJET_CLIENT') }}"
  ansible_python_interpreter: /usr/bin/python3
