plugin: amazon.aws.aws_ec2
regions:
  - "{{ lookup('env', 'AWS_REGION') }}"
filters:
  tag:Name: "{{ lookup('env', 'DUMP_INSTANCE_NAME') }}"
hostnames:
  - instance-id
compose:
  ansible_host: instance-id
  ansible_aws_ssm_instance_id: instance-id
