plugin: amazon.aws.aws_ec2
regions:
  - ca-central-1

# Filtrage des instances EC2 par tag Name (depuis secret GitHub)
filters:
  instance-state-name: running
  tag:Name: "{{ INSTANCE_NAME }}"

# Le hostname sera le tag Name
hostnames:
  - tags.Name

# L'adresse réelle pour se connecter via SSM
compose:
  ansible_host: instance_id

# Création d'un groupe dynamique basé sur le tag Name
groups:
  "{{ INSTANCE_NAME }}": all



# Contrainte pour les noms des host_vars
# plugin: amazon.aws.aws_ec2
# regions:
#   - ca-central-1
# filters:
#   instance-state-name: running
#   tag:Name: BastionHost
# hostnames:
#   - instance_id
# compose:
#   ansible_host: instance_id


