---
- name: Run Database Export Playbook
  hosts: all
  gather_facts: no

  pre_tasks:
    - name: Ensure common packages are installed
      import_tasks: general/install-common-packages.yml
      become: true

    - name: Install Amazon AWS Ansible Collection
      import_tasks: aws/install-ansible-collection-amazon.yml

  tasks:
    - name: Ensure Docker is installed
      import_tasks: general/install-docker.yml
      become: true

    - name: Export Database
      import_tasks: general/run-export-db.yml
